### ISSUE TITLE
Shap explainer tests failing due to new sklearn version

### ISSUE THREAD

**Issue by ascillitoe** [SeldonIO/alibi#564] opened 2021-12-31 12:42 UTC
The `test_shap_wrappers.py` tests are failing due to a change to the LASSO least angle regression solver (`linear_model.LassoLarsIC`) in `sklearn == 1.0.2` (see [here](https://github.com/glemaitre/scikit-learn/blob/e3474785c8c0e51b81e6f063b80529ab10f3b0d0/sklearn/linear_model/_least_angle.py#L2268-L2275)). A `ValueError` is raised when the number of samples is less than the number of features, due to the inaccuracy of estimating the noise variance in this case. 

`LassoLarsIC` is being used *under-the-hood* by `shap` in `shap/explainers/_kernel.py`, so we cannot provide an estimate of the noise variance ourselves. We could wait for a fix on the `shap` side, but it might be worth increasing the number of rows used in the tests (or decrease cols) in the meantime. Alternatively, we could just set `sklearn<1.0.2` for now...

**Comment by jklaise** [comment] 2022-01-05 09:21
Preliminary debugging revealed that the issue is not a simple function of the shape of the original data. Rather what is fed into the `LassoLarsIC` internally is some data-dependent transformation (something like number of sampled coalitions x number of changed features, but would need to refer back to the algorithm details). I've run the notebooks which work, so for now it's just our tests, we will need to wait and see if the issue persists on any real use cases (also by monitoring the [shap issues](https://github.com/slundberg/shap/issues) section). My guess as to why our tests are affected would be due to the randomness in the mock data and the mock predictor which may cause the data-dependent transformation to be rather "unhelpful".

**Comment by jklaise** [comment] 2022-07-04 19:08
Closed via #705.

**Closed by jklaise** 2022-07-04 19:08 UTC
Labels: Priority: Medium
